### PR TITLE
Extend info for list command

### PR DESCRIPTION
**Pull request by mparadinha**
Added the `--extend` option and the funcionality. Decided to not color that part of the output, but that can be easily changed later. 
mal

The date show as NA if nothing was in the api call.

Relevant issue: #5

### CODE REVIEW

**Comment by alexkubica** [comment]
About the date it would be nice If the user could choose the format in some way, maybe via the configurations?
Not related to your PR: when the score is undefined I think it should be replaced wiht a hyphen: `-` which is also the behaviour on the website. Maybe I'll open a new issue for that.

**Comment by mparadinha** [comment]
Yeah those sound like good ideas. The hyphen should be fairly easy. What kind of formats do you think would be nice?

**Comment by alexkubica** [comment]
I think a standard [ISO 8601](http://www.iso.org/iso/iso8601) is the way to go. You could check out this [SO questoin](http://stackoverflow.com/questions/14524322/how-to-convert-a-date-string-to-different-format) for an idea on how you could implement it.

**Comment by ryukinix** [comment]
That's is ok for now. We can implement the other features in another PRs. Thanks for this.

**Comment by ryukinix** [comment]
@AlexK-IL, about the score I changed that on the last PR #36 (implementing drop command)

About the other ideas, we can create issues. @AlexK-IL or @mparadinha, I'll create a issue about date format configuration and then someone of you can create a description, right?

BTW, we can use the default file configuration for store credentials.

**Pull request merged**
