### PR TITLE
Refactor command line interface

### PR DESCRIPTION
**Pull request by alexkubica**
For issue #10

### CODE REVIEW

**Comment by ryukinix** [comment]
Well, we has a problem here. If you see the new `dev` branch I removed that useless commits mine in the last merge on master. You can rebase your branch based on the new dev/master branch? See head commit of the new dev: https://github.com/ryukinix/mal/commits/dev

I think this can help you:

``` bash
git remote add upstream git@github.com:ryukinix/mal.git
git checkout parse_args
git rebase -i @~40
# ... (drop all my commits based on that PR, just write 'd' on the each line start)
git fetch upstream/dev
git rebase upstream/dev
git log
# check if is every ok,
# the last commit before yours need be: 3a910ae1ca5be19db962d3b35eb9849df7233336
# push your changes to your repo
git push --force origin parse_args
```

Sorry for this mess! :( I need think again about squash, this is very bad do directly on active branchs like `dev`.

**Comment by ryukinix** [comment]
I protected this branch too and disabled squash button. At least this don't will occurs again.

**Comment by alexkubica** [comment]
I hope I got your intentions, I deleted all commits between my commits and dev's branch head commit.
Please check if it's ok.

**Comment by ryukinix** [comment]
Thanks! This was exactly I request for you.

**Comment by ryukinix** [comment]
:heart:, BTW, I tested your implementation here. Thanks! This is really much more sane xD

When you have more time, i'll be glad for more help.

**Comment by alexkubica** [comment]
Sure :)
I'll help with the other issues too.

**Pull request merged**
