### PR TITLE
add tests to cover api retreive anime list

### PR DESCRIPTION
**Pull request by xxami**
currently working on adding manga support to api and wanted some tests first to work from. i saw there is an issue about this but doesn't seem to be progress?

only covers list api happy path right now; i wanted to open pr early before i write lots of code that's not going to be merged :P 

so, let me know if the approach is okay and i could continue to add more full coverage to the api

https://travis-ci.org/xxami/mal/jobs/291137211

### CODE REVIEW

**Comment by ryukinix** [comment]
Finallyy the tests!!!!!!!!! oh man, this so good. I'm really happy about that!

**Comment by ryukinix** [comment]
That are really simple tests, but thank you to providing that. I've been procrastinating that for a lot of time, as you probably saw. 

I only need that a `__main__.py` file be added to I be able to run `coverage` tool easily as `coverage run tests`. I already wrote a file, if this PR was marked as editable, I will send a new commit to your branch.

**Comment by ryukinix** [comment]
Seems I don't have permissions to make change on your repo. That's fine.

Please, make that steps on your own fork local copy:
```
git checkout feature/api-unit-tests
git fetch https://github.com/ryukinix/mal.git
git cherry-pick 7dc33b0f5e
git push -u origin feature/api-unit-tests
```

**Review by ryukinix — CHANGES_REQUESTED** [review]
Just cherry-pick the commit with the `__main__.py` file and we have done here.

**Comment by xxami** [comment]
have added that :)
i think the ci failure on this change is a mistake, it's passing on mine and i think it should pass on re-run

**Comment by ryukinix** [comment]
@xxami yes, clearly travis problem. I restarted the job.

**Review by ryukinix — APPROVED** [review]

**Comment by ryukinix** [comment]
LGTM. Merging

**Pull request merged**
